### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by Nihlus** [libratbag/ratbagd#12]
ratbagd raises a "Permission Denied" error when run. No more information is given by the program. libratbag is installed to /usr/local/lib, and ratbagd has been compiled using the provided makefiles using a simple
    make && sudo make install

This is on Linux Mint 18, systemd 229, libratbag 3.0.1. The daemon is started via the systemd service.

**Comment by bentiss** [comment]
You probably need to make sure the permissions files are installed properly, following this [link](https://github.com/libratbag/ratbagd#running-ratbagd).

**Comment by Nihlus** [comment]
That step is performed automatically using make install. The service is properly installed.

**Comment by Hjdskes** [comment]
@Nihlus Does this issue still occur for you with the new Meson build system? I just compiled and installed ratbagd from the current master and do not get the issue anymore, while I did get it before.

**Comment by Nihlus** [comment]
I don't think it's occuring any longer. However, I cannot use piper for some reason, so I'm having trouble testing it. Running ratbagd as sudo works fine, as a user it does not - I hope the dbus invocations have the same result.

**Comment by whot** [comment]
note that ratbagd needs to run as root because it needs access to the hidraw devices. That's the reason ratbad exists, it has the privileges and exports the access via DBus, but whatever is talking to us via DBus doesn't need those same privs.

So I think we can close this one now

**Comment by mercster** [comment]
Incorrectly closed, this happens when run as root.  This has something to do with the user needing to be in some group, but I'm not sure what it is.

```
merc@fedora:~/piper/libratbag$ sudo /usr/local/bin/ratbagd --verbose
Starting ratbagd version 0.18 (API version 2)
Initializing libratbag
ratbagd error: Failed to start ratbagd: Permission denied
```

**Comment by mercster** [comment]
> note that ratbagd needs to run as root because it needs access to the hidraw devices. That's the reason ratbad exists, it has the privileges and exports the access via DBus, but whatever is talking to us via DBus doesn't need those same privs.
> 
> So I think we can close this one now
ping
