### ISSUE TITLE
cp: cannot stat 'ratbagd.service': No such file or directory

### ISSUE THREAD

**Issue by Chronigan** [libratbag/ratbagd#32]
Hello again. I hate to be a bother but after compiling and installing ratbagd I try and install the dbus  portion as it states to do. However after each command I get the these errors.

```
richard@Mercury ~ $ sudo cp dbus/org.freedesktop.ratbag1.conf /etc/dbus-1/system.d/org.freedesktop.ratbag1.conf
[sudo] password for richard: 
cp: cannot stat 'dbus/org.freedesktop.ratbag1.conf': No such file or directory
richard@Mercury ~ $ sudo cp dbus/org.freedesktop.ratbag1.service /etc/dbus-1/system-services/org.freedesktop.ratbag1.conf
cp: cannot stat 'dbus/org.freedesktop.ratbag1.service': No such file or directory
richard@Mercury ~ $ sudo cp ratbagd.service /etc/systemd/system/ratbagd.service
cp: cannot stat 'ratbagd.service': No such file or directory

```
I was also wondering if there are any plans to create a package for this project and put it in a repository?

**Comment by Hjdskes** [comment]
Grmbl, another oversight we missed when switching to Meson.

Try this, from the toplevel source directory (e.g. `~/ratbagd` if you cloned the repository into your home directory:

```
$ sudo cp dbus/org.freedesktop.ratbag1.conf /etc/dbus-1/system.d/org.freedesktop.ratbag1.conf
$ sudo cp builddir/org.freedesktop.ratbag1.service /etc/dbus-1/system-services/org.freedesktop.ratbag1.conf
$ sudo cp builddir/ratbagd.service /etc/systemd/system/ratbagd.service
```

If you used any other build directory (i.e. not simply `builddir` as suggested in the README) adjust accordingly.

**Comment by Hjdskes** [comment]
> I was also wondering if there are any plans to create a package for this project and put it in a repository?

I don't think this is up to us (more something for distribution packagers), but I could be wrong here. In any case, development is still ongoing so it might not be wise to package just yet (i.e. see #31 and https://github.com/libratbag/libratbag/issues/179)

**Comment by bentiss** [comment]
>> I was also wondering if there are any plans to create a package for this project and put it in a repository?

> I don't think this is up to us (more something for distribution packagers), but I could be wrong here. In any case, development is still ongoing so it might not be wise to package just yet (i.e. see #31 and libratbag/libratbag#179)

Well, there are already packages for Arch, Debian and Fedora (not ratbagd for Fedora I must confess). But yeah, it's up to people willing to maintain those package in their distro to add those packages.

**Comment by erdincay** [comment]
> Grmbl, another oversight we missed when switching to Meson.
> 
> Try this, from the toplevel source directory (e.g. `~/ratbagd` if you cloned the repository into your home directory:
> 
> ```
> $ sudo cp dbus/org.freedesktop.ratbag1.conf /etc/dbus-1/system.d/org.freedesktop.ratbag1.conf
> $ sudo cp builddir/org.freedesktop.ratbag1.service /etc/dbus-1/system-services/org.freedesktop.ratbag1.conf
> $ sudo cp builddir/ratbagd.service /etc/systemd/system/ratbagd.service
> ```
> 
> If you used any other build directory (i.e. not simply `builddir` as suggested in the README) adjust accordingly.

**the last line is the solution to my unit file not found issue, thank you**
