### ISSUE TITLE
cp: cannot create regular file

### ISSUE THREAD

**Issue by Chronigan** [libratbag/ratbagd#34]
When I run

`sudo cp builddir/org.freedesktop.ratbag1.service /etc/dbus-1/system-services/org.freedesktop.ratbag1.conf`

i recieve the error

`cp: cannot create regular file '/etc/dbus-1/system-services/org.freedesktop.ratbag1.conf': No such file or directory`

**Comment by bentiss** [comment]
> `cp: cannot create regular file '/etc/dbus-1/system-services/org.freedesktop.ratbag1.conf': No such file or directory`

You might be missing `/etc/dbus-1/system-services/`. IIRC, this is not created by default on most distributions.
