### ISSUE TITLE
Switch capabilities to an enumerated ints

### ISSUE THREAD

**Issue by whot** [libratbag/ratbagd#9]
Strings are nice for development but not ideal because of locale issues

**Comment by Hjdskes** [comment]
This seems to have been implemented (https://github.com/libratbag/ratbagd/pull/10/commits/ca2f32ea58b4a7f1276032fed3ff1526bc705797, https://github.com/libratbag/ratbagd/commit/00f488dc13301b0af532bc3de3f783cbd7f48191, #10), so this issue can be closed I think.

**Comment by whot** [comment]
yep, thanks
